[build]
  command = "npm run build"
  publish = "."
  functions = "netlify/functions"
[[redirects]]
  from = "http://kentrin.com/*"
  to = "https://kentrin.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/explorer"
  to = "/explorer/index.html"
  status = 200
[[redirects]]
  from = "/explorer/*"
  to = "/explorer/index.html"
  status = 200